version: '3'
services:
  db:
    image: microsoft/mssql-server-linux #:2017-GA
    #volumes:
      #- db-data:/var/opt/mssql/
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd!
      MSSQL_PID: Express
      MSSQL_LCID: 1041
      MSSQL_COLLATION: Japanese_CI_AS
    ports:
      - "1433:1433"

volumes:
  db-data:
    driver: local
